apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-svc
  template:
    metadata:
      labels:
        app: hello-svc
    spec:
      containers:
      - name: hello-svc
        image: newmanconnection/hello-svc
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /rest/ping
            port: http
          failureThreshold: 10
          periodSeconds: 30
        resources:
          limits:
            memory: "200Mi"
        env:
        - name: ES_JAVA_OPTS 
          value: "-Xmx128m -Xms128m"
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              name: nc-db-config
              key: db_type
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: nc-db-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: nc-db-config
              key: db_port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nc-db-config
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nc-db-config
              key: db_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: nc-db-config
              key: db_name
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-config
              key: jwt-key
        - name: JWT_ISSUER
          valueFrom:
            secretKeyRef:
              name: jwt-config
              key: jwt-issuer
---
kind: Service
apiVersion: v1
metadata:
  name: hello-svc
spec:
  selector:
    app: hello-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
